### PR TITLE
Add options to retrieve LDAP group membership

### PR DESCRIPTION
**Pull request by aocole**
This change allows the user to configure an additional query that will retrieve the users LDAP group membership and populate it under the "extra" key in the returned auth hash. This is implemented in a way that is very similar to how the filter option was recently implemented. Tests and updated README included.

### CODE REVIEW

**Comment by sammarx** [comment]
+1. Any chance this is going to get merged?

**Comment by MrBerg** [comment]
Same question, only 3 years later. This is a necessary feature.

**Comment by vchrizz** [comment]
Same question, only again ~2 years later. What needs to be done to merge this PR ?

**Comment by Sebastian9628414501** [comment]
@tmilewski @miketierney @ Maintainers Are you willing to accept such a pull request? The functionality to sync groups would be helpful for many plugins such as discourse-ldap-auth. If so, I can provide an updated patch set.

**Comment by vchrizz** [comment]
At the moment I see this message:

> This branch has conflicts that must be resolved
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

So I guess this PR needs to be adapted for correct merge, @aocole would you update your pull request as it's already 8 years old?
In the hope maintainers would merge it.

**Comment by aocole** [comment]
> So I guess this PR needs to be adapted for correct merge, @aocole would you update your pull request as it's already 8 years old? In the hope maintainers would merge it.

@vchrizz I'm no longer at @hpcloud and I don't have write access to the repo to update this PR. Sorry! You're welcome to take the code do it if you're interested!

**Comment by aocole** [comment]
Wow, 10 years. Hard to believe. There are so many people I want to thank. First of all, obviously, Omniauth and the omniauth-ldap library for being my inspiration and my rock through all of this. Without you this PR never could have stayed open this long. Also have to thank HP Cloud for paying me to do this work originally. Shout out to @ingydotnet and Jeff Hobbs (hey ActiveState folks!) for getting me connected to that job. And finally, to all the commenters and fans on this PR over the years - thank you! I dedicate this to you.

**Pull request closed without merging**
